export const QUERY_KEYS = {
  USERS: {
    GET_USER_BALANCE: "GET_USER_BALANCE",
  },
  TODOS: {
    GET_TODOS: "GET_TODOS",
    GET_TODO_OWNER: "GET_TODO_OWNER",
    CREATE_TODO: "CREATE_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    DELETE_TODO: "DELETE_TODO",
  },
};
